zotero:
  user_id: ${oc.env:ZOTERO_ID}
  api_key: ${oc.env:ZOTERO_KEY}
  exclude_path: "20260205_文献引用协助查找/**"

email:
  sender: ${oc.env:SENDER}
  receiver: ${oc.env:RECEIVER}
  smtp_server: smtp.qq.com
  smtp_port: 465
  sender_password: ${oc.env:SENDER_PASSWORD}

llm:
  api:
    key: ${oc.env:OPENAI_API_KEY}
    base_url: ${oc.env:OPENAI_API_BASE}
  generation_kwargs:
    model: gpt-5.2-medium
  language: Chinese

source:
  arxiv:
    category: ["cond-mat.mtrl-sci","cond-mat.dis-nn","cond-mat.stat-mech","physics.comp-ph"]

executor:
  debug: ${oc.env:DEBUG,null}
  max_paper_num: 30
  source: ['arxiv']
